SET IDENTITY_INSERT [dbo].[Prvky] ON
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (1, N'Basic Spin', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (2, N'Inverted V', N'Intermediate', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (3, N'Shoulder Mount', N'Advanced', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (4, N'Fireman Spin', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (5, N'Climb', N'Intermediate', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (6, N'Air Walk', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (7, N'Albatros', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (8, N'Baby Angel', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (9, N'Back Support Tuck', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (10, N'Ballerina Spin', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (11, N'Boomerang', N'Beginner', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (12, N'Butterfly Handstand', N'Beginner', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (13, N'Genie', N'Beginner', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (14, N'Bird', N'Intermediate', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (15, N'Brass Monkey', N'Intermediate', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (16, N'Butterfly', N'Intermediate', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (17, N'Cupid', N'Intermediate', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (18, N'Dakini', N'Intermediate', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (19, N'Flatline', N'Intermediate', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (20, N'Inverted Crucifix', N'Intermediate', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (21, N'Archer', N'Advanced', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (22, N'Ayesha', N'Advanced', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (23, N'Floating Queen', N'Advanced', 0)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (24, N'Janeiro', N'Advanced', 1)
INSERT INTO [dbo].[Prvky] ([Id], [Nazev], [Obtiznost], [Inverted]) VALUES (25, N'Pegasus', N'Advanced', 1)
SET IDENTITY_INSERT [dbo].[Prvky] OFF
